mysqlhost: '34.80.54.17'
user: 'backup'
passwd: 'Jc-12345'
port: '3306'
restorehost: '35.234.13.191'
restoreuser: 'dump'
restorepwd: 'Jc-12345'
restoreport: '3306'
outputpath: '/var/backup/SQL/'
days: '3'
table: 'electronic_game_lobby/game'
data: 
  - 'champion_portal'
  - 'sports_game'
  - 'fantasy_sport'
  - 'electronic_game_lobby'
  - 'game_crazy_pot'
  - 'game_flame_777'
  - 'game_full_tiger_money'
  - 'game_super_8'
  - 'game_emperor_qin'
  - '06_golden_stone_age'
  - '08_guan_yun_chan'
  - '09_egyptian_pharaoh'
  - '11_emperor_qin_plus'
