mysqlhost: '34.80.54.17'
user: 'backup'
passwd: 'Jc-12345'
port: '3306'
restorehost: '10.8.144.29'
restoreuser: 'dump'
restorepwd: 'Jc-12345'
restoreport: '3306'
outputpath: './'
days: '3'
data: 'champion_portal,sports_game,fantasy_sport'
