mysqlhost: '34.80.54.17'
user: 'backup'
passwd: 'Jc-12345'
port: '3306'
restorehost: '35.234.13.191'
restoreuser: 'dump'
restorepwd: 'Jc-12345'
restoreport: '3306'
outputpath: './'
days: '3'
data: 'sports_game,fantasy_sport,game_crazy_pot'
