mysqlhost: '34.80.54.17'
user: 'backup'
passwd: 'Jc-12345'
port: '3306'
restorehost: '35.234.13.191'
restoreuser: 'dump'
restorepwd: 'Jc-12345'
restoreport: '3306'
outputpath: './'
days: '3'
table: 'electronic_game_lobby/game'
data: 'electronic_game_lobby'
